spring:
  datasource:
    url: jdbc:mysql://localhost:3306/share_a_ride_3?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB