spring:
  datasource:
    url: jdbc:mysql://b9e4e7d51c5d3c:8aa5cf60@eu-cdbr-west-03.cleardb.net/heroku_fe056b150e7a326?reconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: b9e4e7d51c5d3c
    password: 8aa5cf60
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB